### ISSUE TITLE
structlog should be optional

### ISSUE THREAD

**Issue by zupo** [niteoweb/pyramid_mixpanel#11]
Same as in https://github.com/niteoweb/pyramid_heroku, usage of [`structlog`](http://www.structlog.org/en/stable/) should be optional so that people that do not use structlog can use `pyramid_mixpanel`.

**Comment by am-on** [comment]
Done in https://github.com/niteoweb/pyramid_mixpanel/commit/a56d61da3a2c10939124d0e1232747a858b84e80
