### ISSUE TITLE
Bug in distinct_id_is_required?

### ISSUE THREAD

**Issue by karantan** [niteoweb/pyramid_mixpanel#16]
I think `distinct_id_is_required` has a bug but I'm not 100% sure.  This https://github.com/niteoweb/pyramid_mixpanel/blob/master/pyramid_mixpanel/track.py#L30 should be `if not self.user.distinct_id:` because `self` is `pyramid_mixpanel.track.MixpanelTrack` object.

Screenshot:

<img width="1024" alt="Screenshot 2019-08-30 09 49 35" src="https://user-images.githubusercontent.com/7062631/64002921-7df81580-cb0b-11e9-9b9e-edf49b6f5f80.png">

**Comment by zupo** [comment]
`MixpanelTrack.user` was removed a while ago and replaced by `MixpanelTrack.distinct_id`: https://github.com/niteoweb/pyramid_mixpanel/commit/a04a56bddb5fd5df4a6683b78eb13902f8e3a447
